spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=TensorTubeDB
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false

# Max file size.
spring.servlet.multipart.max-file-size: 5GB
# Max request size.
spring.servlet.multipart.max-request-size: 5GB

home.path: D:\\home\\
catalog:
  temp: temp\\
  main: main\\
  video: video\\
  tensor: tensor\\

pb.file: tensorflow_inception_graph.pb
labels.file: labels.txt

process.file.cron: 0/5 * * * * ?
thread.pool.size: 10
image.thread.pool.size: 5
process.file.time.frame: 5